### ISSUE TITLE
MQTT name that starts with the device name Error in Home Assistant 2023.08

### ISSUE THREAD

**Issue by gllmlbrt** [LordMike/MBW.BlueRiiot2MQTT#80]
As of 2023.08 we get a warning on all entities that the entity name is the same as the device name and that will no longer be accepted as per Hass 2024.02 (Leaves us some time).
![image](https://github.com/LordMike/MBW.BlueRiiot2MQTT/assets/58825251/1b3faa82-9847-498e-b9f2-d388ba2a7e58)
In the above case, I have two "devices" in the Blue Connect app, called "Pool" and "Vildmarksbad".

I believe it requires that the add-on creates the entity with a different nameing convention than just the device-name_suffix.
Adding a prefix ?

Or is this something we shoudl change in the configuration somewhere?

**Comment by gllmlbrt** [comment]
I realise this maybe should have been posted to the Hass Add-on page instead. Let me know if you want it tidy and reposted there or something else ?

**Comment by DAVIZINH0** [comment]
as i read yesterday this is a future issue with the MQTT. not only addons. Any device that report information to homeassistant by mqtt protocol have this future problem. Now is only a advertise.

in this post they expain better than me :-)

[https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099](https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099)

**Comment by LordMike** [comment]
I added device names as prefixes because it's my opinion that "sensor.ph" is useless .. but I guess they will add it themselves?

If so, I'll have to make an update that changes the "unique_id" - I hope it won't break everything :|

Oh - and this is the correct repo. Hass-addons repo is purely for the addon.

**Comment by LordMike** [comment]
A bit more docs are here:
https://www.home-assistant.io/blog/2023/08/02/release-20238/#breaking-changes

Expanding the "MQTT" accordion will show notes on the name changes.

**Comment by LordMike** [comment]
I've pushed an update, 0.15.0 - try it out and let me know.

**Comment by gllmlbrt** [comment]
> I've pushed an update, 0.15.0 - try it out and let me know.

Hey, 
I deleted all the entities/devices, stopped the add-on, updated and restarted. Naturally it found all the deveices and recreated the devices and entitites in Hass, but they are the same entities names, therefore same alert.
So:
A. whatever you edited did not break anything. Still works as before.
B. Did not resolve the naming warning from Hass/MQTT.

The entities have unique IDs, which among other things allow to change many things from the UI like icon, decimals names etc..

I was thinking you could add a prefix directly in the creation of the entity.
Granted that sensor.ph woudl be useless. 
Right now it is sensor.pool_ph which trigger the warrning because "pool" is the name of the device as well.
To remove the warning and resolve the 2024.02 ultimatum, would be to have it as sensor.prefix_pool_ph.
Prefix could be "blueriiot" ?

**Comment by LordMike** [comment]
That’s true. I could add a configuration element to control what the prefix should be. Weird that it didn’t remove it though - the warning is gone on my end :|

Mike.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LordMike** [comment]
I noticed some more entities that I'd missed, api operational and so on. Latest versions should resolve this.

I've also found on other projects that the warning does not disappear immediately, but over time. So could you check again?
